spring:
  application:
    name: infra-devices-service
  config:
    import: "configserver:"
  profiles:
    active: prod #dev
  cloud:
    config:
      uri: http://infra-config-server:8888 #http://localhost:8888